name: fuodz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.3+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_theme: ^1.1.0
  basic_utils: ^2.5.3
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.16.0+1
  contained_tab_bar_view: ^0.7.1
  cool_alert: ^1.0.3
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.0
  dartx: ^0.5.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  dotted_border: ^1.0.7
  dotted_line: ^2.0.2
  firebase_auth: ^0.20.0+1
  firebase_chat: ^0.0.3
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flag: ^3.1.0
  flutter_icons: ^1.0.0+1
  flutter_local_notifications: ^3.0.2
  flutter_onboard: ^0.1.0
  flutter_rating_bar: ^4.0.0
  flutter_staggered_animations: ^0.1.2
  flutter_webview_plugin: ^0.3.11
  geocoder: ^0.2.1
  google_fonts: ^0.4.0
  google_map_location_picker: ^4.1.6
  google_maps_flutter: ^1.2.0
  google_nav_bar: ^5.0.3
  google_places_flutter: ^2.0.3
  group_radio_button: ^1.0.1
  i18n_extension: ^4.0.0
  image_picker: ^0.6.7+17
  in_app_review: ^1.0.4
  inspection: ^0.0.12
  jiffy: ^3.0.1
  line_icons: ^0.2.0
  location: ^3.2.1
  map_launcher: ^1.1.2
  package_info: ^0.4.3+2
  pin_code_fields: ^6.1.0
  pretty_dio_logger: ^1.1.1
  provider: ^4.3.2+3
  pull_to_refresh: ^1.6.4
  qr_flutter: ^4.0.0
  random_string: ^2.1.0
  rx_shared_preferences: ^1.3.5
  share: ^2.0.1
  shared_preferences: ^0.5.10
  smooth_page_indicator: ^0.2.3
  stacked: ^1.7.6
  sticky_headers: ^0.1.8+1
  supercharged: ^2.0.0
  url_launcher: ^5.5.0
  velocity_x: ^2.6.0
  what3words: ^3.0.4

dependency_overrides:
  flutter_svg: ^0.19.3
  intl: ^0.17.0
  args: ^2.0.0
  flutter_application_id: ^1.0.0
  flutter_polyline_points: ^0.2.4
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_application_id: "^1.0.0"
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
